[project]
name = "chargepal-monitor-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "nicegui>=2.1.0",
    "toml>=0.10.2",
    "rich>=13.8.0",
]
